### ISSUE TITLE
We've built WebflowSync on top of webflow-ruby!

### ISSUE THREAD

**Issue by vfonic** [penseo/webflow-ruby#13]
Hey @phoet!

Thank you for creating webflow-ruby!

Just wanted to let you know that @stankovicjovana, @markokacanski and I built `webflow_sync` gem that syncs Rails models to WebFlow. The gem has been developed over the past couple of days, but we plan to keep adding new features and using it in live webapp soon.

I'd be curious to hear your thoughts, especially if you need a similar functionality.

Thanks!
Viktor

**Comment by phoet** [comment]
@vfonic 👍 

i'm currently not developing anything based on the gem, so i don't really have a usecase to test you gem (link for the lazy https://github.com/vfonic/webflow_sync)

please feel free to add a new section to the readme hinting your gem if you like.

**Comment by vfonic** [comment]
Thank you! I appreciate it!

I've also added a mention to webflow-ruby in our readme: https://github.com/vfonic/webflow_sync#thanks-and-credits
