### ISSUE TITLE
webflow-ruby is not compatible with http v5

### ISSUE THREAD

**Issue by vfonic** [penseo/webflow-ruby#20]
Hey,

I just ran `bundle update` and it updated 'http' gem from v4.4.1 to v5.

Seems like 'http' v5 does not have method `request` here:
https://github.com/penseo/webflow-ruby/blob/master/lib/webflow/client.rb#L130

Maybe the 'http' dependency version number should be restricted? Or some other method could be used to get request data?

PS This is their changelog: https://github.com/httprb/http/blob/master/CHANGES.md#500-2021-05-12

**Comment by phoet** [comment]
did you have issues with webmock maybe? https://github.com/bblimke/webmock/pull/941#issuecomment-841184715

**Comment by vfonic** [comment]
@phoet indeed! It works with webmock 3.13.0, but doesn't work with 3.12.0

Do you think you should restrict webflow-ruby dependencies somehow so that other developers don't hit this issue?

**Comment by phoet** [comment]
also, this project has a Gemfile.lock checked into the repo. i know that this goes against some recommendations for best practices, but this type of error is exactly what i do it. other developers are guaranteed to have a working environment out of the box.

**Comment by vfonic** [comment]
How did it happen in my case then?

There is a http/webmock version combination that is not compatible. If someone has `gem 'webmock', '3.12.0'` in their `Gemfile`, it's possible that they install `webflow-ruby` and the gem doesn't work for them. But I guess that's a very rare case.
