### ISSUE TITLE
Let consumers of the gem handle pagination

### ISSUE THREAD

**Issue by emilesilvis** [penseo/webflow-ruby#9]
Currently the gem [paginates for you](https://github.com/penseo/webflow-ruby/blob/a9d519c3f4fa84abd339ea274fe6c0a92bfd171b/lib/webflow/client.rb#L58), often leading to the rate limit being hit and [difficult-to-handle exceptions](https://github.com/penseo/webflow-ruby/pull/7) being thrown. While I think it's good to introduce an [exception for when the rate limit is hit](https://github.com/penseo/webflow-ruby/blob/a9d519c3f4fa84abd339ea274fe6c0a92bfd171b/lib/webflow/client.rb#L126), I also think that pagination should be left up to the consumer of the gem (as mentioned [here](https://github.com/penseo/webflow-ruby/pull/7#issuecomment-563081874)). 

That way, we don't end up with being half-way through iterating through a collection and then getting the `RateLimitError` thrown. Plus, then it's a more faithful mirroring of the actual RESTful API.

Thoughts?

**Comment by phoet** [comment]
sure, this can become anoying quickly.

i think a simple solution could be allow an optional block on the method that yields the chunks.

by asking the client about the [current rate-limit](https://github.com/penseo/webflow-ruby/blob/master/lib/webflow/client.rb#L131-L134) additional measures could be taken, i guess that only sleeping is likely to help?

**Comment by emilesilvis** [comment]
Yeah, yielding the block does indeed seem like a good solution.

Yes, indeed what I do now - I wrap calls to the gem in a method that sleeps
when the rate limit is  low.

Op ma 9 dec. 2019 om 08:56 schreef Peter Schröder <notifications@github.com>

**Comment by phoet** [comment]
closed by 40b981efbb24691f498e0957b935724738194f8e

@emilesilvis if you like, you could try version 1.1.0 that has just been pushed

**Comment by emilesilvis** [comment]
Awesome, thanks @phoet ❤️
